### ISSUE TITLE
Flathub Gedit always uses GTK file dialog when run on non-GNOME platforms

### ISSUE THREAD

**Issue by Pointedstick** [flathub/org.gnome.gedit#1]
Flatpacked Gedit from Flathub does not display the native, platform-specific file chooser when run in:
- Kubuntu 17.10
- KDE Plasma 5.12.2
- Flatpak 0.8.7

Steps to reproduce:
1. Install Gedit from Flathub using the command line or KDE Discover, makes no difference

2. Install xdg-desktop-portal and xdg-desktop-portal-kde
```
$  sudo apt install xdg-desktop-portal xdg-desktop-portal-kde               
Reading package lists... Done                                                             
Building dependency tree                                                                  
Reading state information... Done                                                         
xdg-desktop-portal is already the newest version (0.8-2).                                 
xdg-desktop-portal-kde is already the newest version (5.12.2-0ubuntu1~ubuntu17.10~ppa1).  
0 upgraded, 0 newly installed, 0 to remove and 94 not upgraded.
```

3. manually set GTK_USE_PORTAL=1
```
$  export GTK_USE_PORTAL=1
nate@Spectre:~$  echo $GTK_USE_PORTAL
1
```

4. Run gedit:
$  `flatpak run org.gnome.gedit`

5. In Gedit, click Open > Other Documents

Expected results:
The native KDE file dialog is shown

Actual results:
The GTK file dialog is shown, not the KDE one

**Comment by Pointedstick** [comment]
Never mind, not a packaging issue. See https://bugzilla.gnome.org/show_bug.cgi?id=793695.

**Comment by TingPing** [comment]
It probably doesn't use `GtkFileChooserNative`. It also doesn't have a maintainer AFAIK.

**Comment by Pointedstick** [comment]
No maintainer for the flagship text editor, that seems like a problem...

**Comment by TingPing** [comment]
Thankfully text editing doesn't change much and GtkSourceview is still maintained where the bulk of the complexity is.

**Comment by Bachsau** [comment]
It's more likely that `GtkFileChooserNative` doesn't support it. If it weren't using it, file browsing wouldn't work at all.

**Comment by jbicha** [comment]
I believe this is fixed in gedit 3.30.0

**Comment by Pointedstick** [comment]
It was, but that change was later reverted in https://gitlab.gnome.org/World/gedit/gedit/-/commit/74e0be7e8419d3dbbb6554a9b2315b59b693846e. As a result, this is a still a problem. I have submitted https://github.com/flathub/org.gnome.gedit/pull/172 to fix it in the Flathub packaging, since it doesn't look like an upstream solution to use the portal dialog is something that's going to happen soon.
